# Generated by Django 4.2.1 on 2023-07-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.PositiveBigIntegerField(default=6000000000, help_text='Please Enter the Balance Amount of this User into the Bank', verbose_name='Balance of Bank Account Card'),
            preserve_default=False,
        ),
    ]
