# Generated by Django 4.2.1 on 2023-07-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_users_alter_comment_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='users',
            new_name='liked_users',
        ),
    ]
